resumes/res_app/urls.py
from django.urls import path

from res_app import views

app_name='res_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('resumes/', views.ResumeList.as_view(), name='resume-list'),
    path('resume/<int:pk>/', views.ResumePrinter.as_view(), name='res-pdf'),
    path('resume/<int:pk>/preview/', views.ResumeModelView.as_view(), name='res-preview')
]

resumes/resumes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("res_app.urls")),
]

resumes/res_app/models.py
from django.db import models
from django.urls import reverse



SHORT_FORMAT = '%b %Y'
KSA_TYPES=(
    ('sk', 'Skill'),
    ('tc', 'Technology'),
)
# Create your models here.

class PhoneNumber(models.Model):
    """
    A simple model capturing phone numbers
    """
    # CHOICES
    TYPES = (
        ('h', 'Home'),
        ('w', 'Work'),
        ('m', 'Mobile')
    )
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='PhoneNumber_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='PhoneNumber_modified')
    phone_number = models.CharField(max_length=100, null=True, blank=True, help_text='Enter your phone number')
    type = models.CharField(max_length=1, choices=TYPES, null=True, blank=True, help_text='The type of phone number represented by this record')

    class Meta:
        app_label = 'res_app'

    def __str__(self):
        return self.phone_number

class SocialMedia(models.Model):
    """
    A simple model to house social media accounts we wish to share.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='SocialMedia_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='SocialMedia_modified')
    media_name = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the social media platform (e.g. GitHub)')
    href = models.URLField(max_length=200, null=True, blank=True, help_text='The URL used to connect to this social media profile')
    icon = models.CharField(max_length=200, null=True, blank=True, help_text='The Font Awesome icon code to be applied.')

    def __str__(self):
        return self.media_name

    class Meta:
        app_label = 'res_app'
        verbose_name_plural = 'Social Media'

class Address(models.Model):
    """
    A simple model for capturing a physical address
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Address_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Address_modified')
    street_1 = models.CharField(max_length=100, null=True, blank=True, help_text='First line in a street address')
    street_2 = models.CharField(max_length=100, null=True, blank=True, help_text='Second line for street address')
    street_3 = models.CharField(max_length=100, null=True, blank=True, help_text='Third line in street address')
    city = models.CharField(max_length=100, null=True, blank=True, help_text='City')
    state = models.CharField(max_length=2, null=True, blank=True)
    zip_code = models.CharField(max_length=15, null=True, blank=True)

    class Meta:
        app_label = 'res_app'

    def __str__(self):
        return self.street_1 + ', ' + self.city


class ContactInfo(models.Model):
    """
    A model of contact information, linking to a given user
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='ContactInfo_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='ContactInfo_modified')
    person = models.ForeignKey('auth.User', null=True, on_delete=models.SET_NULL)
    phone_numbers = models.ManyToManyField(PhoneNumber)
    email = models.EmailField(null=True, blank=True, help_text='Enter a valid email address')
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL)
    social_media = models.ManyToManyField(SocialMedia)

    class Meta:
        app_label = 'res_app'
        verbose_name_plural = "Contact Info"

    def __str__(self):
        return self.person.get_full_name() + " contact info"

class KSA(models.Model):
    """
    A model capturing records of Knowledge, Skills, and Abilities.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='KSA_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='KSA_modified')
    name = models.CharField(max_length=100, null=True, blank=True, help_text='The short name for this KSA')
    years = models.FloatField(default=0, help_text='The number of years experience with this KSA')
    description = models.TextField(help_text='A description of this particular KSA')
    type = models.CharField(max_length=2, choices=KSA_TYPES, null=True, blank=True, help_text='The type of knowledge, skill, or ability this record represents')

    class Meta:
        app_label = 'res_app'
        verbose_name_plural = 'KSAs'

    def __str__(self):
        return self.name + ' ' + str(self.years) + ' years'

class Employment(models.Model):
    """
    A model for employment history
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Employment_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Employment_modified')
    employer = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the employer')
    position = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the position held at this employer')
    start_date = models.DateField(help_text='The approximate start date for this employment')
    end_date = models.DateField(help_text='The approximate end date for this employment', blank=True, null=True)
    description = models.TextField(help_text='A description of this employment')
    ksas = models.ManyToManyField(KSA, help_text='The Knowledge, Skills, and Abilities used in this employment', verbose_name="KSA's")

    class Meta:
        app_label = 'res_app'
        ordering = ['-start_date', ]

    def get_start_date(self):
        return self.start_date.strftime(SHORT_FORMAT)

    def get_end_date(self):
        return self.end_date.strftime(SHORT_FORMAT) if self.end_date else 'Present'

    def __str__(self):
        return self.employer + ": " + self.start_date.strftime(SHORT_FORMAT) + ' - ' + self.get_end_date()

class Project(models.Model):
    """
    A model for capturing individual projects (like GitHub repos) that you may want to include on a resume.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Project_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Project_modified')
    name = models.CharField(max_length=200, null=True, blank=True, help_text='The brief name of this projects')
    url = models.URLField(max_length=200, null=True, blank=True, help_text='A URL to point people towards this project')
    description = models.TextField(help_text='A description of this project')

    class Meta:
        app_label = 'res_app'

    def __str__(self):
        return self.name

class EducationHistory(models.Model):
    """
    A model to capture specific education histories.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Eduction_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Eduction_modified')
    institution = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the educational institution')

resumes/res_app/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User

from django_weasyprint import WeasyTemplateResponseMixin
from custom.mixins import JsonTemplateMixin

from res_app import models
from resumes import settings


class IndexView(generic.TemplateView):
    """
    The home page for the Resume App
    """
    template_name = 'res_app/index.html'

class ResumeModelView(generic.DetailView):
    """
    A parent CBV for our PDF printing view
    """
    model = models.Resume

    # Overriding the default get_template_names() function
    # to allow us to dynamically select template names from
    # the admin console
    def get_template_names(self):
        return self.object.template_name

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['skills'] = models.KSA.objects.filter(type='sk')
        context['tech'] = models.KSA.objects.filter(type='tc')

        return context

class ResumePrinter(WeasyTemplateResponseMixin, ResumeModelView):
    """
    This view generates the PDF of the resume template
    """
    pdf_attachment=False
    pdf_filename = 'resume.pdf'


    def get_pdf_stylesheets(self):
        return [
        settings.STATIC_ROOT + '/res_app/css/' + self.object.css_file_name, ]

class ResumeList(JsonTemplateMixin, generic.ListView):
    """
    A simple JSON list of available resumes to convert to PDFs
    """
    model = User
    template_name = 'res_app/resume_list.html'

    # Filtering the user list to only those with resumes.
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['user_list'] = User.objects.filter(resume__isnull=False).distinct()
        return context

resumes/res_app/templates/res_app/resume_templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'res_app/css/basic.css' %}">
  </head>
  <body>
    <header class="w-100 gd-steel {% if not resume.summaery %} bottom-b{% endif %}">
      <!-- Contact Information Here -->
      <div class="row w-80">
        <div class="col s8">
          <h3 class="indigo-text text-darken-4 tight-y">
            {{resume.person.first_name}}
          </h3>
          <h3 class="indigo-text text-darken-4 tight-y">
            {{resume.person.last_name}}
          </h3>
        </div>
        <div class="col s4">
          <h5 class="indigo-text text-darken-4S tight-y">Contact Info</h5>
          {% if resume.person.contactinfo_set.first.address.street_1 %}
          <p class="contact-info">
            {{resume.person.contactinfo_set.first.address.street_1}}, {% if resume.person.contactinfo_set.first.address.street_2 %}{{resume.person.contactinfo_set.first.address.street_2}}{% endif %}
          </p>
          {% endif %}
          {% if resume.person.contactinfo_set.first.address.street_3 %}
          <p class="contact-info">
            {{resume.person.contactinfo_set.first.address.street_3}}
          </p>
          {% endif %}
          {% if resume.person.contactinfo_set.first.address.city %}
          <p class="contact-info">
          {{resume.person.contactinfo_set.first.address.city}}{% if resume.person.contactinfo_set.first.address.state %}, {{resume.person.contactinfo_set.first.address.state}}
          {% endif %} {% if resume.person.contactinfo_set.first.address.zip_code %}
          {{resume.person.contactinfo_set.first.address.zip_code}}
          {% endif %}
          </p>
          {% endif %}
          {% if resume.person.contactinfo_set.first.email %}
          <p class="contact-info"><a href="mailto:{{resume.person.contactinfo_set.first.email}}">{{resume.person.contactinfo_set.first.email}}</a></p>
          {% endif %}
          {% for pnum in resume.person.contactinfo_set.first.phone_numbers.all  %}
             {% if forloop.first %}

             {% endif %}
                 <p class="contact-info">{{pnum.phone_number}} - {{pnum.get_type_display}}</p>
             {% if forloop.last %}

             {% endif %}
          {% empty %}

          {% endfor %}
        </div>
      </div>
    </header>
    <main>
      <!-- Summary Sectio - Bordered -->
      {% if resmue.summary %}
      <div class="row summary">
        <p>{{resume.summary}}</p>
      </div>
      {% else %}

      {% endif %}
      <div class="row ksas-projects">
        <div class="col s6">
          {% for ksa in resume.ksas.all  %}
             {% if forloop.first %}

                <h6 class="indigo-text text-darken-4 center gd-steel">
                  Knowledge, Skills, and Abilities
                </h6>
                <ul class="outer-list">
             {% endif %}
                  <li><b>{{ksa.name}} - {{ksa.years}} Years</b></li>
                  <ul class="inner-list">
                    <li>{{ksa.description|truncatechars:100}}</li>
                  </ul>
             {% if forloop.last %}
                </ul>
             {% endif %}
          {% empty %}

          {% endfor %}
        </div>
        <div class="col s6">
          {% for proj in resume.projects.all %}
             {% if forloop.first %}
                <h6 class="indigo-text text-darken-4 center gd-steel">Projects</h6>
                <ul class='projects'>
             {% endif %}
                <li>
                  <span class="mt-1"><b class="left-align">{{proj.name}}</b>  <a href="{{proj.url}}" class="right-align">{{proj.url}}</a></span>

                  <p class="tight-y">{{proj.description}}</p>
                </li>
             {% if forloop.last %}
                </ul>
             {% endif %}
          {% empty %}

          {% endfor %}

        </div>
      </div>

      {% for emp in resume.employment_histories.all  %}
         {% if forloop.first %}
            <div class="row emps">
              <h6 class="center indigo-text text-darken-4 gd-steel">Employment History</h6>
         {% endif %}
            <div class="row emp">
              <div class="col s3 emp-dates center">
                <p>{{emp.get_start_date}}</p>
                <p class='date-divider'></p>
                <p>{{emp.get_end_date}}</p>
              </div>
              <div class="col s9 emp-details">
                <p class="company_name">{{emp.employer}}</p>
                <p class="position">{{emp.position}}</p>
                <p class="duties">{{emp.description}}</p>
              </div>
            </div>
         {% if forloop.last %}
          </div>
         {% endif %}
      {% empty %}

      {% endfor %}
    </main>
  </body>
</html>

resumes/res_app/templates/res_app/resume_templates/paper.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat|Noto+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'res_app/css/paper.css' %}">
    <link rel="stylesheet" href="{% static 'res_app/css/typography.css' %}">
  </head>
  <body>
    <section class="sheet">
      <aside class="">
        <section class="contact-info">
          <h5 class="contact">Contact</h5>
            <ul class="blank">
              <li><i class="fas fa-map-marker-alt"></i> {{resume.person.contactinfo_set.first.address.city}}{% if resume.person.contactinfo_set.first.address.state %}, {{resume.person.contactinfo_set.first.address.state}}
              {% endif %}</li>
              {% if resume.person.contactinfo_set.first.email %}
              <li><i class="fas fa-envelope"></i> <a href="mailto:{{resume.person.contactinfo_set.first.email}}">{{resume.person.contactinfo_set.first.email}}</a></li>
              {% endif %}
            </ul>
        </section>
        <section class="ksas">
            <h5>Technical Skills</h5>
            <ul>
              {% for t in tech %}
                <li>{{t.name}} - {{t.years}}</li>
              {% endfor %}
            </ul>
            <h5>Abilities</h5>
            <ul>
              {% for s in skills %}
                <li>{{s.name}} - {{s.years}}</li>
              {% endfor %}
            </ul>
        </section>
      </aside>
      <section class="main">
        <header>
        <text class="name">  {{resume.person.first_name}} {{resume.person.last_name}} </text>
        <text class="headline">{{resume.headline}}</text>
        <hr>
        </header>
        {% if resume.summary %}
          <section class="summary"></section>
        {% endif %}
        <secion class="experience">
          {% for emp in resume.employment_histories.all  %}
             {% if forloop.first %}
              <h5>Experience</h5>
             {% endif %}
              <h5><span class="align-left">{{emp.employer}}</span> <span class="align-right">{{emp.get_start_date}} - {{emp.get_end_date}}</span></h5>
             {% if forloop.last %}
              <hr>
             {% endif %}
          {% empty %}

          {% endfor %}
        </secion>
      </section>
    </section>
  </body>
</html>

resumes/res_app/templates/res_app/resume_templates/swiss.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ resume.person.get_full_name }} Resume</title>

</head>
<body>

</body>
</html>