resumes/res_app/urls.py
from django.urls import path

from res_app import views

app_name='res_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('resumes/', views.ResumeList.as_view(), name='resume-list'),
    path('resume/<int:pk>/', views.ResumePrinter.as_view(), name='res-pdf'),
    path('resume/<int:pk>/preview/', views.ResumeModelView.as_view(), name='res-preview')
]

resumes/resumes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("res_app.urls")),
]

resumes/res_app/models.py
from django.db import models
from django.urls import reverse



SHORT_FORMAT = '%b %Y'
KSA_TYPES=(
    ('sk', 'Skill'),
    ('tc', 'Technology'),
)
# Create your models here.

class PhoneNumber(models.Model):
    """
    A simple model capturing phone numbers
    """
    # CHOICES
    TYPES = (
        ('h', 'Home'),
        ('w', 'Work'),
        ('m', 'Mobile')
    )
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='PhoneNumber_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='PhoneNumber_modified')
    phone_number = models.CharField(max_length=100, null=True, blank=True, help_text='Enter your phone number')
    type = models.CharField(max_length=1, choices=TYPES, null=True, blank=True, help_text='The type of phone number represented by this record')

    class Meta:
        app_label = 'res_app'

    def __str__(self):
        return self.phone_number

class SocialMedia(models.Model):
    """
    A simple model to house social media accounts we wish to share.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='SocialMedia_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='SocialMedia_modified')
    media_name = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the social media platform (e.g. GitHub)')
    href = models.URLField(max_length=200, null=True, blank=True, help_text='The URL used to connect to this social media profile')
    icon = models.CharField(max_length=200, null=True, blank=True, help_text='The Font Awesome icon code to be applied.')

    def __str__(self):
        return self.media_name

    class Meta:
        app_label = 'res_app'
        verbose_name_plural = 'Social Media'

class Address(models.Model):
    """
    A simple model for capturing a physical address
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Address_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Address_modified')
    street_1 = models.CharField(max_length=100, null=True, blank=True, help_text='First line in a street address')
    street_2 = models.CharField(max_length=100, null=True, blank=True, help_text='Second line for street address')
    street_3 = models.CharField(max_length=100, null=True, blank=True, help_text='Third line in street address')
    city = models.CharField(max_length=100, null=True, blank=True, help_text='City')
    state = models.CharField(max_length=2, null=True, blank=True)
    zip_code = models.CharField(max_length=15, null=True, blank=True)

    class Meta:
        app_label = 'res_app'

    def __str__(self):
        return self.street_1 + ', ' + self.city


class ContactInfo(models.Model):
    """
    A model of contact information, linking to a given user
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='ContactInfo_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='ContactInfo_modified')
    person = models.ForeignKey('auth.User', null=True, on_delete=models.SET_NULL)
    phone_numbers = models.ManyToManyField(PhoneNumber)
    email = models.EmailField(null=True, blank=True, help_text='Enter a valid email address')
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL)
    social_media = models.ManyToManyField(SocialMedia)

    class Meta:
        app_label = 'res_app'
        verbose_name_plural = "Contact Info"

    def __str__(self):
        return self.person.get_full_name() + " contact info"

class KSA(models.Model):
    """
    A model capturing records of Knowledge, Skills, and Abilities.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='KSA_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='KSA_modified')
    name = models.CharField(max_length=100, null=True, blank=True, help_text='The short name for this KSA')
    years = models.FloatField(default=0, help_text='The number of years experience with this KSA')
    description = models.TextField(help_text='A description of this particular KSA')
    type = models.CharField(max_length=2, choices=KSA_TYPES, null=True, blank=True, help_text='The type of knowledge, skill, or ability this record represents')

    class Meta:
        app_label = 'res_app'
        verbose_name_plural = 'KSAs'

    def __str__(self):
        return self.name + ' ' + str(self.years) + ' years'

class Employment(models.Model):
    """
    A model for employment history
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Employment_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Employment_modified')
    employer = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the employer')
    position = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the position held at this employer')
    start_date = models.DateField(help_text='The approximate start date for this employment')
    end_date = models.DateField(help_text='The approximate end date for this employment', blank=True, null=True)
    description = models.TextField(help_text='A description of this employment')
    ksas = models.ManyToManyField(KSA, help_text='The Knowledge, Skills, and Abilities used in this employment', verbose_name="KSA's")

    class Meta:
        app_label = 'res_app'
        ordering = ['-start_date', ]

    def get_start_date(self):
        return self.start_date.strftime(SHORT_FORMAT)

    def get_end_date(self):
        return self.end_date.strftime(SHORT_FORMAT) if self.end_date else 'Present'

    def __str__(self):
        return self.employer + ": " + self.start_date.strftime(SHORT_FORMAT) + ' - ' + self.get_end_date()

class Project(models.Model):
    """
    A model for capturing individual projects (like GitHub repos) that you may want to include on a resume.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Project_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Project_modified')
    name = models.CharField(max_length=200, null=True, blank=True, help_text='The brief name of this projects')
    url = models.URLField(max_length=200, null=True, blank=True, help_text='A URL to point people towards this project')
    description = models.TextField(help_text='A description of this project')

    class Meta:
        app_label = 'res_app'

    def __str__(self):
        return self.name

class EducationHistory(models.Model):
    """
    A model to capture specific education histories.
    """
    date_created = models.DateTimeField(auto_now_add=True, help_text='date record created.')
    date_modified = models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')
    created_by = models.ForeignKey('auth.User', help_text='user who created record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Eduction_created')
    modified_by=models.ForeignKey('auth.User', help_text='user who most recently modified record.', null=True, blank=True, on_delete=models.SET_NULL, related_name='Eduction_modified')
    institution = models.CharField(max_length=200, null=True, blank=True, help_text='The name of the educational institution')

resumes/res_app/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User

from django_weasyprint import WeasyTemplateResponseMixin
from custom.mixins import JsonTemplateMixin

from res_app import models
from resumes import settings


class IndexView(generic.TemplateView):
    """
    The home page for the Resume App
    """
    template_name = 'res_app/index.html'

class ResumeModelView(generic.DetailView):
    """
    A parent CBV for our PDF printing view
    """
    model = models.Resume

    # Overriding the default get_template_names() function
    # to allow us to dynamically select template names from
    # the admin console
    def get_template_names(self):
        return self.object.template_name

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['skills'] = models.KSA.objects.filter(type='sk')
        context['tech'] = models.KSA.objects.filter(type='tc')

        return context

class ResumePrinter(WeasyTemplateResponseMixin, ResumeModelView):
    """
    This view generates the PDF of the resume template
    """
    pdf_attachment=False
    pdf_filename = 'resume.pdf'


    def get_pdf_stylesheets(self):
        return [
        settings.STATIC_ROOT + '/res_app/css/' + self.object.css_file_name, ]

class ResumeList(JsonTemplateMixin, generic.ListView):
    """
    A simple JSON list of available resumes to convert to PDFs
    """
    model = User
    template_name = 'res_app/resume_list.html'

    # Filtering the user list to only those with resumes.
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['user_list'] = User.objects.filter(resume__isnull=False).distinct()
        return context

resumes/res_app/templates/res_app/base.html
The outer most Django template, mostly just used to import common static files.
-->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{title|default:"Resumes"}}</title>
  </head>

  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat" rel="stylesheet">

  {% block more_style %}
  <!-- Additional Style Rules can be loaded here -->
  {% endblock %}
  <body>
    {% block main %}
    <!-- Most content will be loaded here. -->
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block more_scripts %}
    <!-- Additional Javascript can be loaded here -->
    {% endblock %}
  </body>
</html>

resumes/res_app/templates/res_app/index.html
{% extends "res_app/base.html" %}

{% load static %}

{% block more_style %}
  <link rel="stylesheet" href="{% static 'res_app/css/index.css' %}">
{% endblock %}

{% block main %}
  <main class="dark-trans-50">
    <ul id="user-dropdown" class="dropdown-content">
      <li><i class="material-icons">face</i> Username: admin</li>
      <li><i class="material-icons">lock</i> Password: pass</li>
    </ul>
    <nav>
      <div class="nav-wrapper dark-trans-50">
        <a href="" class="brand-logo">Resume Builder</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/admin"><i class="material-icons">build</i></a></li>
        </ul>
        <a href="#" data-target="slide-out" class="sidenav-trigger left hide-on-large-and-up"><i class="material-icons">menu</i></a>
        <ul class="right">
          <li>
            <a href="#!" data-target="user-dropdown" class="dropdown-trigger">
              <i class="material-icons">supervisor_account</i>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <ul id="slide-out" class="sidenav">
      <li><a href="/admin"><i class="material-icons">build</i> Builder Interface</a></li>
    </ul>
    <div class="container h-90">
      <div class="valign-wrapper h-80">
        <div class="js-load-div container" data-url="{% url 'res_app:resume-list' %}">
          <!-- Resumes loaded here -->
        </div>
      </div>
    </div>

  </main>
{% endblock %}

{% block more_scripts %}
  <script src="{% static 'res_app/js/index.js' %}" charset="utf-8"></script>
  <script type="text/javascript">

    document.addEventListener('DOMContentLoaded', function () {
      resApp.loadDivs()
      M.AutoInit();
    })
  </script>
{% endblock %}

resumes/res_app/templates/res_app/resume_list.html
{% for person in user_list  %}
<div class="row">
  <div class="card w-100 col s12">
    <div class="card-content">
      <span class="card-title">Resumes for {{person.get_full_name}}</span>
      <ul class="collection">
        {% for resume in person.resume_set.all  %}
          <li class="collection-item">
            <div>
              <h5 class="indigo-text text-darken-3">
                  {{resume.name|capfirst}} <a href="{% url 'res_app:res-preview' pk=resume.id %}" class="secondary-content"><i class="material-icons">find_in_page</i></a> <a href="{{resume.get_absolute_url}}" target="" class="secondary-content"><i class="material-icons">picture_as_pdf</i></a>
              </h5>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endfor %}